import type { ProgramPreset } from '../types';

export const PHAT: ProgramPreset = {
  id: 'phat',
  name: 'PHAT',
  shortDescription: 'Five training days mixing two heavy power days with three hypertrophy days.',
  description:
    'A five-day split that opens the week with two heavy power days (low reps, long rest) and follows with three hypertrophy days organised by body part. Take rest days between blocks (e.g. Mon/Tue power, Wed rest, Thu/Fri/Sat hypertrophy). Add weight on the power lifts when you hit the top of the 3–5 rep range; on hypertrophy work, progress when you hit the top of the 8–15 rep range.',
  daysPerWeek: 5,
  experienceLevel: 'advanced',
  source: { label: 'Power Hypertrophy Adaptive Training split (5-day)' },
  defaultUnit: 'kg',
  workouts: [
    {
      key: 'upper-power',
      name: 'Upper Power',
      exercises: [
        {
          match: { normalizedName: 'pendlay row' },
          targetSets: 3,
          targetReps: null,
          restSeconds: 180,
          progression: { rule: 'double', repRangeMin: 3, repRangeMax: 5, incrementKg: 2.5, incrementLb: 5 },
        },
        {
          match: { normalizedName: 'pull up' },
          targetSets: 2,
          targetReps: null,
          restSeconds: 150,
          progression: { rule: 'double', repRangeMin: 6, repRangeMax: 10 },
        },
        {
          match: { normalizedName: 'barbell bench press' },
          targetSets: 3,
          targetReps: null,
          restSeconds: 180,
          progression: { rule: 'double', repRangeMin: 3, repRangeMax: 5, incrementKg: 2.5, incrementLb: 5 },
        },
        {
          match: { normalizedName: 'incline dumbbell bench press' },
          targetSets: 2,
          targetReps: null,
          restSeconds: 150,
          progression: { rule: 'double', repRangeMin: 6, repRangeMax: 10, incrementKg: 2, incrementLb: 5 },
        },
        {
          match: { normalizedName: 'overhead press' },
          targetSets: 3,
          targetReps: null,
          restSeconds: 150,
          progression: { rule: 'double', repRangeMin: 6, repRangeMax: 10, incrementKg: 2.5, incrementLb: 5 },
        },
        {
          match: { normalizedName: 'skull crusher' },
          targetSets: 3,
          targetReps: null,
          restSeconds: 90,
          progression: { rule: 'double', repRangeMin: 6, repRangeMax: 10, incrementKg: 2, incrementLb: 5 },
        },
        {
          match: { normalizedName: 'barbell curl' },
          targetSets: 3,
          targetReps: null,
          restSeconds: 90,
          progression: { rule: 'double', repRangeMin: 6, repRangeMax: 10, incrementKg: 2, incrementLb: 5 },
        },
      ],
    },
    {
      key: 'lower-power',
      name: 'Lower Power',
      exercises: [
        {
          match: { normalizedName: 'barbell back squat' },
          targetSets: 3,
          targetReps: null,
          restSeconds: 240,
          progression: { rule: 'double', repRangeMin: 3, repRangeMax: 5, incrementKg: 2.5, incrementLb: 5 },
        },
        {
          match: { normalizedName: 'hack squat' },
          targetSets: 2,
          targetReps: null,
          restSeconds: 180,
          progression: { rule: 'double', repRangeMin: 6, repRangeMax: 10, incrementKg: 5, incrementLb: 10 },
        },
        {
          match: { normalizedName: 'romanian deadlift' },
          targetSets: 3,
          targetReps: null,
          restSeconds: 180,
          progression: { rule: 'double', repRangeMin: 5, repRangeMax: 8, incrementKg: 2.5, incrementLb: 5 },
        },
        {
          match: { normalizedName: 'lying leg curl' },
          targetSets: 2,
          targetReps: null,
          restSeconds: 120,
          progression: { rule: 'double', repRangeMin: 6, repRangeMax: 10, incrementKg: 2.5, incrementLb: 5 },
        },
        {
          match: { normalizedName: 'standing calf raise machine' },
          targetSets: 3,
          targetReps: null,
          restSeconds: 75,
          progression: { rule: 'double', repRangeMin: 6, repRangeMax: 10, incrementKg: 2.5, incrementLb: 5 },
        },
        {
          match: { normalizedName: 'seated calf raise machine' },
          targetSets: 2,
          targetReps: null,
          restSeconds: 75,
          progression: { rule: 'double', repRangeMin: 6, repRangeMax: 10, incrementKg: 2.5, incrementLb: 5 },
        },
      ],
    },
    {
      key: 'back-shoulders-hypertrophy',
      name: 'Back & Shoulders Hypertrophy',
      exercises: [
        {
          match: { normalizedName: 'barbell row' },
          targetSets: 3,
          targetReps: null,
          restSeconds: 120,
          progression: { rule: 'double', repRangeMin: 8, repRangeMax: 12, incrementKg: 2.5, incrementLb: 5 },
        },
        {
          match: { normalizedName: 'lat pulldown' },
          targetSets: 3,
          targetReps: null,
          restSeconds: 90,
          progression: { rule: 'double', repRangeMin: 8, repRangeMax: 12, incrementKg: 2.5, incrementLb: 5 },
        },
        {
          match: { normalizedName: 'seated cable row' },
          targetSets: 3,
          targetReps: null,
          restSeconds: 90,
          progression: { rule: 'double', repRangeMin: 8, repRangeMax: 12, incrementKg: 2.5, incrementLb: 5 },
        },
        {
          match: { normalizedName: 'dumbbell shoulder press' },
          targetSets: 3,
          targetReps: null,
          restSeconds: 120,
          progression: { rule: 'double', repRangeMin: 8, repRangeMax: 12, incrementKg: 2, incrementLb: 5 },
        },
        {
          match: { normalizedName: 'dumbbell lateral raise' },
          targetSets: 3,
          targetReps: null,
          restSeconds: 75,
          progression: { rule: 'double', repRangeMin: 8, repRangeMax: 12, incrementKg: 1, incrementLb: 2.5 },
        },
        {
          match: { normalizedName: 'cable face pull' },
          targetSets: 3,
          targetReps: null,
          restSeconds: 60,
          progression: { rule: 'double', repRangeMin: 12, repRangeMax: 15, incrementKg: 1, incrementLb: 2.5 },
        },
      ],
    },
    {
      key: 'lower-hypertrophy',
      name: 'Lower Hypertrophy',
      exercises: [
        {
          match: { normalizedName: 'barbell back squat' },
          targetSets: 3,
          targetReps: null,
          restSeconds: 120,
          progression: { rule: 'double', repRangeMin: 8, repRangeMax: 12, incrementKg: 2.5, incrementLb: 5 },
          notes: 'Use a moderately lighter weight than Lower Power day.',
        },
        {
          match: { normalizedName: 'leg press' },
          targetSets: 3,
          targetReps: null,
          restSeconds: 120,
          progression: { rule: 'double', repRangeMin: 10, repRangeMax: 15, incrementKg: 5, incrementLb: 10 },
        },
        {
          match: { normalizedName: 'lying leg curl' },
          targetSets: 4,
          targetReps: null,
          restSeconds: 90,
          progression: { rule: 'double', repRangeMin: 8, repRangeMax: 12, incrementKg: 2.5, incrementLb: 5 },
        },
        {
          match: { normalizedName: 'walking lunge' },
          targetSets: 3,
          targetReps: null,
          restSeconds: 90,
          progression: { rule: 'double', repRangeMin: 8, repRangeMax: 12, incrementKg: 2, incrementLb: 5 },
        },
        {
          match: { normalizedName: 'standing calf raise machine' },
          targetSets: 4,
          targetReps: null,
          restSeconds: 60,
          progression: { rule: 'double', repRangeMin: 10, repRangeMax: 15, incrementKg: 2.5, incrementLb: 5 },
        },
      ],
    },
    {
      key: 'chest-arms-hypertrophy',
      name: 'Chest & Arms Hypertrophy',
      exercises: [
        {
          match: { normalizedName: 'incline dumbbell bench press' },
          targetSets: 3,
          targetReps: null,
          restSeconds: 120,
          progression: { rule: 'double', repRangeMin: 8, repRangeMax: 12, incrementKg: 2, incrementLb: 5 },
        },
        {
          match: { normalizedName: 'dumbbell bench press' },
          targetSets: 3,
          targetReps: null,
          restSeconds: 120,
          progression: { rule: 'double', repRangeMin: 8, repRangeMax: 12, incrementKg: 2, incrementLb: 5 },
        },
        {
          match: { normalizedName: 'pec deck' },
          targetSets: 3,
          targetReps: null,
          restSeconds: 75,
          progression: { rule: 'double', repRangeMin: 10, repRangeMax: 15, incrementKg: 2.5, incrementLb: 5 },
        },
        {
          match: { normalizedName: 'cable tricep pushdown' },
          targetSets: 3,
          targetReps: null,
          restSeconds: 75,
          progression: { rule: 'double', repRangeMin: 10, repRangeMax: 15, incrementKg: 2, incrementLb: 5 },
        },
        {
          match: { normalizedName: 'dumbbell tricep extension' },
          targetSets: 3,
          targetReps: null,
          restSeconds: 75,
          progression: { rule: 'double', repRangeMin: 10, repRangeMax: 15, incrementKg: 2, incrementLb: 5 },
        },
        {
          match: { normalizedName: 'dumbbell bicep curl' },
          targetSets: 3,
          targetReps: null,
          restSeconds: 75,
          progression: { rule: 'double', repRangeMin: 10, repRangeMax: 15, incrementKg: 2, incrementLb: 5 },
        },
        {
          match: { normalizedName: 'hammer curl' },
          targetSets: 3,
          targetReps: null,
          restSeconds: 75,
          progression: { rule: 'double', repRangeMin: 10, repRangeMax: 15, incrementKg: 2, incrementLb: 5 },
        },
      ],
    },
  ],
};
