import type { ProgramPreset } from '../types';

export const PHUL: ProgramPreset = {
  id: 'phul',
  name: 'PHUL',
  shortDescription: 'Four-day Power/Hypertrophy split with separate Upper and Lower days for each.',
  description:
    'A four-day split that pairs two heavy "power" days (low reps, long rest) with two "hypertrophy" days (higher reps, shorter rest). The week splits into Upper Power, Lower Power, Upper Hypertrophy, Lower Hypertrophy. Add weight on power days when you hit the top of the 3–5 rep range across all working sets; treat hypertrophy days as 6–12 / 10–15 rep work and progress when you hit the top of the range.',
  daysPerWeek: 4,
  experienceLevel: 'intermediate',
  source: { label: 'Power Hypertrophy Upper Lower split (4-day)' },
  defaultUnit: 'kg',
  workouts: [
    {
      key: 'upper-power',
      name: 'Upper Power',
      exercises: [
        {
          match: { normalizedName: 'barbell bench press' },
          targetSets: 3,
          targetReps: null,
          restSeconds: 180,
          progression: { rule: 'double', repRangeMin: 3, repRangeMax: 5, incrementKg: 2.5, incrementLb: 5 },
        },
        {
          match: { normalizedName: 'incline dumbbell bench press' },
          targetSets: 3,
          targetReps: null,
          restSeconds: 150,
          progression: { rule: 'double', repRangeMin: 6, repRangeMax: 10, incrementKg: 2, incrementLb: 5 },
        },
        {
          match: { normalizedName: 'barbell row' },
          targetSets: 3,
          targetReps: null,
          restSeconds: 180,
          progression: { rule: 'double', repRangeMin: 3, repRangeMax: 5, incrementKg: 2.5, incrementLb: 5 },
        },
        {
          match: { normalizedName: 'lat pulldown' },
          targetSets: 3,
          targetReps: null,
          restSeconds: 150,
          progression: { rule: 'double', repRangeMin: 6, repRangeMax: 10, incrementKg: 2.5, incrementLb: 5 },
        },
        {
          match: { normalizedName: 'overhead press' },
          targetSets: 2,
          targetReps: null,
          restSeconds: 180,
          progression: { rule: 'double', repRangeMin: 3, repRangeMax: 5, incrementKg: 2.5, incrementLb: 5 },
        },
        {
          match: { normalizedName: 'barbell curl' },
          targetSets: 3,
          targetReps: null,
          restSeconds: 90,
          progression: { rule: 'double', repRangeMin: 6, repRangeMax: 10, incrementKg: 2, incrementLb: 5 },
        },
        {
          match: { normalizedName: 'skull crusher' },
          targetSets: 3,
          targetReps: null,
          restSeconds: 90,
          progression: { rule: 'double', repRangeMin: 6, repRangeMax: 10, incrementKg: 2, incrementLb: 5 },
        },
      ],
    },
    {
      key: 'lower-power',
      name: 'Lower Power',
      exercises: [
        {
          match: { normalizedName: 'barbell back squat' },
          targetSets: 3,
          targetReps: null,
          restSeconds: 240,
          progression: { rule: 'double', repRangeMin: 3, repRangeMax: 5, incrementKg: 2.5, incrementLb: 5 },
        },
        {
          match: { normalizedName: 'barbell deadlift' },
          targetSets: 3,
          targetReps: null,
          restSeconds: 240,
          progression: { rule: 'double', repRangeMin: 3, repRangeMax: 5, incrementKg: 5, incrementLb: 10 },
        },
        {
          match: { normalizedName: 'leg press' },
          targetSets: 3,
          targetReps: null,
          restSeconds: 150,
          progression: { rule: 'double', repRangeMin: 10, repRangeMax: 15, incrementKg: 5, incrementLb: 10 },
        },
        {
          match: { normalizedName: 'lying leg curl' },
          targetSets: 3,
          targetReps: null,
          restSeconds: 120,
          progression: { rule: 'double', repRangeMin: 6, repRangeMax: 10, incrementKg: 2.5, incrementLb: 5 },
        },
        {
          match: { normalizedName: 'standing calf raise machine' },
          targetSets: 4,
          targetReps: null,
          restSeconds: 75,
          progression: { rule: 'double', repRangeMin: 6, repRangeMax: 10, incrementKg: 2.5, incrementLb: 5 },
        },
        {
          match: { normalizedName: 'seated calf raise machine' },
          targetSets: 4,
          targetReps: null,
          restSeconds: 75,
          progression: { rule: 'double', repRangeMin: 6, repRangeMax: 10, incrementKg: 2.5, incrementLb: 5 },
        },
      ],
    },
    {
      key: 'upper-hypertrophy',
      name: 'Upper Hypertrophy',
      exercises: [
        {
          match: { normalizedName: 'incline barbell bench press' },
          targetSets: 4,
          targetReps: null,
          restSeconds: 120,
          progression: { rule: 'double', repRangeMin: 8, repRangeMax: 12, incrementKg: 2.5, incrementLb: 5 },
        },
        {
          match: { normalizedName: 'cable fly' },
          targetSets: 3,
          targetReps: null,
          restSeconds: 90,
          progression: { rule: 'double', repRangeMin: 8, repRangeMax: 12, incrementKg: 2, incrementLb: 5 },
        },
        {
          match: { normalizedName: 'seated cable row' },
          targetSets: 4,
          targetReps: null,
          restSeconds: 120,
          progression: { rule: 'double', repRangeMin: 8, repRangeMax: 12, incrementKg: 2.5, incrementLb: 5 },
        },
        {
          match: { normalizedName: 'single arm dumbbell row' },
          targetSets: 3,
          targetReps: null,
          restSeconds: 90,
          progression: { rule: 'double', repRangeMin: 8, repRangeMax: 12, incrementKg: 2, incrementLb: 5 },
        },
        {
          match: { normalizedName: 'dumbbell lateral raise' },
          targetSets: 3,
          targetReps: null,
          restSeconds: 75,
          progression: { rule: 'double', repRangeMin: 8, repRangeMax: 12, incrementKg: 1, incrementLb: 2.5 },
        },
        {
          match: { normalizedName: 'hammer curl' },
          targetSets: 3,
          targetReps: null,
          restSeconds: 75,
          progression: { rule: 'double', repRangeMin: 10, repRangeMax: 15, incrementKg: 2, incrementLb: 5 },
        },
        {
          match: { normalizedName: 'rope tricep pushdown' },
          targetSets: 3,
          targetReps: null,
          restSeconds: 75,
          progression: { rule: 'double', repRangeMin: 10, repRangeMax: 15, incrementKg: 2, incrementLb: 5 },
        },
      ],
    },
    {
      key: 'lower-hypertrophy',
      name: 'Lower Hypertrophy',
      exercises: [
        {
          match: { normalizedName: 'barbell front squat' },
          targetSets: 3,
          targetReps: null,
          restSeconds: 150,
          progression: { rule: 'double', repRangeMin: 8, repRangeMax: 12, incrementKg: 2.5, incrementLb: 5 },
        },
        {
          match: { normalizedName: 'hack squat' },
          targetSets: 3,
          targetReps: null,
          restSeconds: 120,
          progression: { rule: 'double', repRangeMin: 8, repRangeMax: 12, incrementKg: 5, incrementLb: 10 },
        },
        {
          match: { normalizedName: 'walking lunge' },
          targetSets: 3,
          targetReps: null,
          restSeconds: 120,
          progression: { rule: 'double', repRangeMin: 8, repRangeMax: 12, incrementKg: 2, incrementLb: 5 },
        },
        {
          match: { normalizedName: 'leg extension' },
          targetSets: 3,
          targetReps: null,
          restSeconds: 75,
          progression: { rule: 'double', repRangeMin: 10, repRangeMax: 15, incrementKg: 2.5, incrementLb: 5 },
        },
        {
          match: { normalizedName: 'lying leg curl' },
          targetSets: 3,
          targetReps: null,
          restSeconds: 75,
          progression: { rule: 'double', repRangeMin: 10, repRangeMax: 15, incrementKg: 2.5, incrementLb: 5 },
        },
        {
          match: { normalizedName: 'seated calf raise machine' },
          targetSets: 4,
          targetReps: null,
          restSeconds: 60,
          progression: { rule: 'double', repRangeMin: 10, repRangeMax: 15, incrementKg: 2.5, incrementLb: 5 },
        },
      ],
    },
  ],
};
