import type { ProgramPreset } from '../types';

export const REDDIT_PPL: ProgramPreset = {
  id: 'reddit-ppl-6day',
  name: '6-Day Push Pull Legs',
  shortDescription: 'Six training days a week split into Push, Pull, Legs — run twice through.',
  description:
    'A high-frequency hypertrophy split with a Push, Pull and Legs day, each run twice per week. Day A leans heavier on the main compound; Day B uses a different primary lift and slightly higher reps. Use a fixed weight for main compounds and add weight when you hit the top of the rep range on the prescribed sets.',
  daysPerWeek: 6,
  experienceLevel: 'intermediate',
  source: {
    label: 'Inspired by the r/Fitness Push/Pull/Legs structure',
  },
  defaultUnit: 'kg',
  workouts: [
    {
      key: 'push-a',
      name: 'Push A (Heavy Bench)',
      exercises: [
        {
          match: { normalizedName: 'barbell bench press' },
          targetSets: 4,
          targetReps: null,
          restSeconds: 180,
          progression: { rule: 'double', repRangeMin: 6, repRangeMax: 8, incrementKg: 2.5, incrementLb: 5 },
        },
        {
          match: { normalizedName: 'overhead press' },
          targetSets: 3,
          targetReps: null,
          restSeconds: 150,
          progression: { rule: 'double', repRangeMin: 8, repRangeMax: 12, incrementKg: 2.5, incrementLb: 5 },
        },
        {
          match: { normalizedName: 'incline dumbbell bench press' },
          targetSets: 3,
          targetReps: null,
          restSeconds: 120,
          progression: { rule: 'double', repRangeMin: 8, repRangeMax: 10, incrementKg: 2, incrementLb: 5 },
        },
        {
          match: { normalizedName: 'cable fly' },
          targetSets: 3,
          targetReps: null,
          restSeconds: 90,
          progression: { rule: 'double', repRangeMin: 12, repRangeMax: 15, incrementKg: 2, incrementLb: 5 },
        },
        {
          match: { normalizedName: 'cable tricep pushdown' },
          targetSets: 3,
          targetReps: null,
          restSeconds: 90,
          progression: { rule: 'double', repRangeMin: 10, repRangeMax: 12, incrementKg: 2, incrementLb: 5 },
        },
        {
          match: { normalizedName: 'skull crusher' },
          targetSets: 3,
          targetReps: null,
          restSeconds: 90,
          progression: { rule: 'double', repRangeMin: 8, repRangeMax: 10, incrementKg: 2, incrementLb: 5 },
        },
      ],
    },
    {
      key: 'pull-a',
      name: 'Pull A (Heavy Deadlift)',
      exercises: [
        {
          match: { normalizedName: 'barbell deadlift' },
          targetSets: 3,
          targetReps: 5,
          restSeconds: 240,
          progression: { rule: 'linear', incrementKg: 5, incrementLb: 10 },
        },
        {
          match: { normalizedName: 'pull up' },
          targetSets: 3,
          targetReps: null,
          restSeconds: 150,
          progression: { rule: 'double', repRangeMin: 8, repRangeMax: 12 },
          notes: 'Add weight via belt once you hit the top of the rep range on all sets.',
        },
        {
          match: { normalizedName: 'barbell row' },
          targetSets: 3,
          targetReps: null,
          restSeconds: 150,
          progression: { rule: 'double', repRangeMin: 6, repRangeMax: 8, incrementKg: 2.5, incrementLb: 5 },
        },
        {
          match: { normalizedName: 'cable lat pulldown' },
          targetSets: 3,
          targetReps: null,
          restSeconds: 120,
          progression: { rule: 'double', repRangeMin: 10, repRangeMax: 12, incrementKg: 2.5, incrementLb: 5 },
        },
        {
          match: { normalizedName: 'cable face pull' },
          targetSets: 4,
          targetReps: null,
          restSeconds: 60,
          progression: { rule: 'double', repRangeMin: 12, repRangeMax: 15, incrementKg: 1, incrementLb: 2.5 },
        },
        {
          match: { normalizedName: 'barbell curl' },
          targetSets: 3,
          targetReps: null,
          restSeconds: 90,
          progression: { rule: 'double', repRangeMin: 8, repRangeMax: 10, incrementKg: 2, incrementLb: 5 },
        },
        {
          match: { normalizedName: 'hammer curl' },
          targetSets: 3,
          targetReps: null,
          restSeconds: 90,
          progression: { rule: 'double', repRangeMin: 10, repRangeMax: 12, incrementKg: 2, incrementLb: 5 },
        },
      ],
    },
    {
      key: 'legs-a',
      name: 'Legs A (Heavy Squat)',
      exercises: [
        {
          match: { normalizedName: 'barbell back squat' },
          targetSets: 4,
          targetReps: null,
          restSeconds: 180,
          progression: { rule: 'double', repRangeMin: 6, repRangeMax: 8, incrementKg: 2.5, incrementLb: 5 },
        },
        {
          match: { normalizedName: 'romanian deadlift' },
          targetSets: 3,
          targetReps: null,
          restSeconds: 150,
          progression: { rule: 'double', repRangeMin: 8, repRangeMax: 10, incrementKg: 2.5, incrementLb: 5 },
        },
        {
          match: { normalizedName: 'leg press' },
          targetSets: 3,
          targetReps: null,
          restSeconds: 120,
          progression: { rule: 'double', repRangeMin: 10, repRangeMax: 12, incrementKg: 5, incrementLb: 10 },
        },
        {
          match: { normalizedName: 'leg curl' },
          targetSets: 3,
          targetReps: null,
          restSeconds: 90,
          progression: { rule: 'double', repRangeMin: 10, repRangeMax: 12, incrementKg: 2, incrementLb: 5 },
        },
        {
          match: { normalizedName: 'standing calf raise machine' },
          targetSets: 4,
          targetReps: null,
          restSeconds: 60,
          progression: { rule: 'double', repRangeMin: 10, repRangeMax: 12, incrementKg: 2.5, incrementLb: 5 },
        },
        {
          match: { normalizedName: 'hanging leg raise' },
          targetSets: 3,
          targetReps: null,
          restSeconds: 60,
          progression: { rule: 'double', repRangeMin: 10, repRangeMax: 15 },
        },
      ],
    },
    {
      key: 'push-b',
      name: 'Push B (Heavy OHP)',
      exercises: [
        {
          match: { normalizedName: 'overhead press' },
          targetSets: 4,
          targetReps: null,
          restSeconds: 180,
          progression: { rule: 'double', repRangeMin: 6, repRangeMax: 8, incrementKg: 2.5, incrementLb: 5 },
        },
        {
          match: { normalizedName: 'incline barbell bench press' },
          targetSets: 3,
          targetReps: null,
          restSeconds: 150,
          progression: { rule: 'double', repRangeMin: 8, repRangeMax: 10, incrementKg: 2.5, incrementLb: 5 },
        },
        {
          match: { normalizedName: 'dumbbell bench press' },
          targetSets: 3,
          targetReps: null,
          restSeconds: 120,
          progression: { rule: 'double', repRangeMin: 10, repRangeMax: 12, incrementKg: 2, incrementLb: 5 },
        },
        {
          match: { normalizedName: 'dumbbell lateral raise' },
          targetSets: 3,
          targetReps: null,
          restSeconds: 75,
          progression: { rule: 'double', repRangeMin: 12, repRangeMax: 15, incrementKg: 1, incrementLb: 2.5 },
        },
        {
          match: { normalizedName: 'rope tricep pushdown' },
          targetSets: 3,
          targetReps: null,
          restSeconds: 90,
          progression: { rule: 'double', repRangeMin: 10, repRangeMax: 12, incrementKg: 2, incrementLb: 5 },
        },
        {
          match: { normalizedName: 'dumbbell tricep extension' },
          targetSets: 3,
          targetReps: null,
          restSeconds: 90,
          progression: { rule: 'double', repRangeMin: 10, repRangeMax: 12, incrementKg: 2, incrementLb: 5 },
        },
      ],
    },
    {
      key: 'pull-b',
      name: 'Pull B (Heavy Row)',
      exercises: [
        {
          match: { normalizedName: 'barbell row' },
          targetSets: 4,
          targetReps: null,
          restSeconds: 180,
          progression: { rule: 'double', repRangeMin: 6, repRangeMax: 8, incrementKg: 2.5, incrementLb: 5 },
        },
        {
          match: { normalizedName: 'pull up' },
          targetSets: 3,
          targetReps: null,
          restSeconds: 150,
          progression: { rule: 'double', repRangeMin: 8, repRangeMax: 12 },
        },
        {
          match: { normalizedName: 'seated cable row' },
          targetSets: 3,
          targetReps: null,
          restSeconds: 120,
          progression: { rule: 'double', repRangeMin: 10, repRangeMax: 12, incrementKg: 2.5, incrementLb: 5 },
        },
        {
          match: { normalizedName: 'lat pulldown' },
          targetSets: 3,
          targetReps: null,
          restSeconds: 120,
          progression: { rule: 'double', repRangeMin: 10, repRangeMax: 12, incrementKg: 2.5, incrementLb: 5 },
        },
        {
          match: { normalizedName: 'cable face pull' },
          targetSets: 4,
          targetReps: null,
          restSeconds: 60,
          progression: { rule: 'double', repRangeMin: 12, repRangeMax: 15, incrementKg: 1, incrementLb: 2.5 },
        },
        {
          match: { normalizedName: 'dumbbell bicep curl' },
          targetSets: 3,
          targetReps: null,
          restSeconds: 90,
          progression: { rule: 'double', repRangeMin: 10, repRangeMax: 12, incrementKg: 2, incrementLb: 5 },
        },
        {
          match: { normalizedName: 'ez bar curl' },
          targetSets: 3,
          targetReps: null,
          restSeconds: 90,
          progression: { rule: 'double', repRangeMin: 10, repRangeMax: 12, incrementKg: 2, incrementLb: 5 },
        },
      ],
    },
    {
      key: 'legs-b',
      name: 'Legs B (Volume)',
      exercises: [
        {
          match: { normalizedName: 'barbell back squat' },
          targetSets: 4,
          targetReps: null,
          restSeconds: 180,
          progression: { rule: 'double', repRangeMin: 8, repRangeMax: 10, incrementKg: 2.5, incrementLb: 5 },
          notes: 'Use a moderately lighter weight than Legs A — focus on volume.',
        },
        {
          match: { normalizedName: 'barbell front squat' },
          targetSets: 3,
          targetReps: null,
          restSeconds: 150,
          progression: { rule: 'double', repRangeMin: 8, repRangeMax: 10, incrementKg: 2.5, incrementLb: 5 },
        },
        {
          match: { normalizedName: 'walking lunge' },
          targetSets: 3,
          targetReps: null,
          restSeconds: 120,
          progression: { rule: 'double', repRangeMin: 10, repRangeMax: 12, incrementKg: 2, incrementLb: 5 },
        },
        {
          match: { normalizedName: 'leg extension' },
          targetSets: 3,
          targetReps: null,
          restSeconds: 90,
          progression: { rule: 'double', repRangeMin: 12, repRangeMax: 15, incrementKg: 2.5, incrementLb: 5 },
        },
        {
          match: { normalizedName: 'seated calf raise machine' },
          targetSets: 4,
          targetReps: null,
          restSeconds: 60,
          progression: { rule: 'double', repRangeMin: 10, repRangeMax: 15, incrementKg: 2.5, incrementLb: 5 },
        },
        {
          match: { normalizedName: 'cable crunch' },
          targetSets: 3,
          targetReps: null,
          restSeconds: 60,
          progression: { rule: 'double', repRangeMin: 12, repRangeMax: 15, incrementKg: 2.5, incrementLb: 5 },
        },
      ],
    },
  ],
};
